# Configuración de la aplicación
spring.application.name=api-gateway

# Configuración del servidor
server.port=8080

# Configuración de Eureka
eureka.client.serviceUrl.defaultZone=${SPRING_EUREKA_DEFAULT_ZONE}
eureka.client.initialInstanceInfoReplicationIntervalSeconds=5
eureka.client.registryFetchIntervalSeconds=5
eureka.instance.leaseRenewalIntervalInSeconds=5
eureka.instance.leaseExpirationDurationInSeconds=5
eureka.instance.prefer-ip-address=true
# FIN configuracion necesaria para eureka



# Configuración de rutas de Spring Cloud Gateway
spring.cloud.gateway.routes[0].id=cliente-route
spring.cloud.gateway.routes[0].uri=lb://ms-clientes
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/clientes/**

spring.cloud.gateway.routes[0].id=cliente-route
spring.cloud.gateway.routes[0].uri=lb://ms-clientes
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/obras/**

spring.cloud.gateway.routes[1].id=producto-route
spring.cloud.gateway.routes[1].uri=lb://ms-productos
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/productos/**

spring.cloud.gateway.routes[2].id=pedido-route
spring.cloud.gateway.routes[2].uri=lb://ms-pedidos
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/pedidos/**

spring.cloud.gateway.routes[3].id=usuario-route 
spring.cloud.gateway.routes[3].uri=lb://ms-usuarios
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/usuarios/**

spring.cloud.gateway.routes[4].id=docker-route
spring.cloud.gateway.routes[4].uri=lb://ms-docker
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/docker/**

# Configuración adicional (opcional)
management.endpoints.web.exposure.include=*
