spring.application.name=MS-USUARIOS

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# configuracion necesaria para eureka
eureka.client.serviceUrl.defaultZone=${SPRING_EUREKA_DEFAULT_ZONE}
eureka.client.initialInstanceInfoReplicationIntervalSeconds=5
eureka.client.registryFetchIntervalSeconds=5
eureka.instance.leaseRenewalIntervalInSeconds=5
eureka.instance.leaseExpirationDurationInSeconds=5
eureka.instance.prefer-ip-address=true
# FIN configuracion necesaria para eureka
dan.usuarios.instancia=${SPRING_INSTANCIA}
